name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build binaries
      run: |
        # macOS
        GOOS=darwin GOARCH=amd64 go build -o ptn-darwin-amd64 ./cmd
        GOOS=darwin GOARCH=arm64 go build -o ptn-darwin-arm64 ./cmd
        
        # Linux
        GOOS=linux GOARCH=amd64 go build -o ptn-linux-amd64 ./cmd
        GOOS=linux GOARCH=arm64 go build -o ptn-linux-arm64 ./cmd
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ptn-darwin-amd64
          ptn-darwin-arm64
          ptn-linux-amd64
          ptn-linux-arm64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}